### ISSUE TITLE
investigate last login

### ISSUE THREAD

**Issue by pierreozoux** [indiehosters/ownCloud#17]
last login is:

```
select * from oc_preferences;
```

**Comment by pierreozoux** [comment]
The idea is to gather the list of emails that didn't login during the last 3months

Here is the schema:
schema:

| userid                       | appid          | configkey                        | configvalue                                         |
username                     | login          | lastLogin                        | 1459371615                                          |
username                     | settings      | email                            | myemail@myprovider.com

**Comment by sebrosa** [comment]
## Untested query proposal:

`select A.userid, B.configvalue`
`from oc_preferences as A, oc_preferences as B`
`on A.userid = B.userid`
`where A.configkey = "LastLogin"`
`and A.configvalue < date_sub(now(), interval 2 month)`
`and B.configkey   = "email";`

**!! Need to be tested !!**

## Possible problems
- Uppercase issues with configkey - should them be always converted to uppercase in the query to prevent bugs?
- Date math issues if the date format is like seconds since 1/Jan/1970 or so.  Might be better just subtract the number of seconds in 60 days (which is a good enough approach to two months).

## References
- Check recipe for date math at 
  http://stackoverflow.com/questions/4237594/mysql-where-date-is-greater-than-one-month
- Check docs for self join at
  http://www.mysqltutorial.org/mysql-self-join/

**Comment by pierreozoux** [comment]
Great, thanks for your help, will check it and let you know!

**Comment by pierreozoux** [comment]
@sebrosa you were missing the INNER JOIN :)

Here is the definitive query! Thanks a lot for your help!

```
select b.configvalue from oc_preferences a INNER JOIN oc_preferences b ON a.userid = b.userid where a.configkey = "lastLogin"  and a.configvalue < date_sub(now(), interval 2 month) and b.configkey = "email";
```

**Comment by unteem** [comment]
not maintained anymore moved to [nextcloud](https://lab.libreho.st/libre.sh/compose/nextcloud)
